name: CUE CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CUE
        uses: cue-lang/setup-cue@v1.0.1
        with:
          cue-version: "v0.13.0"

      - name: Run CUE tests
        run: cue vet test.cue
